name: flugram
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.2.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.17.5
  uuid: ^4.4.0
  http: ^1.2.1
  url_launcher: ^6.3.0
  blowe_bloc: ^0.3.1
  # blowe_bloc:
  #   git:
  #     url: https://github.com/santiagogonzalezblowe/blowe_bloc.git
  #     ref: add-bloc-property

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/illustrations/
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
