// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwhwQR-_6JxCkHAWcPiB6h4pniSyFLy8Q',
    appId: '1:399674068229:web:646758696ec67e4f4fbb6c',
    messagingSenderId: '399674068229',
    projectId: 'flugram-55f95',
    authDomain: 'flugram-55f95.firebaseapp.com',
    storageBucket: 'flugram-55f95.appspot.com',
    measurementId: 'G-3876WJYNSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd--HPAU4gN1SEP-PYu0n4fG91mD-BExg',
    appId: '1:399674068229:android:b46cfe8ca86845584fbb6c',
    messagingSenderId: '399674068229',
    projectId: 'flugram-55f95',
    storageBucket: 'flugram-55f95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-wqLCR6eoitcRZnaMkdViIuYo7rlO27U',
    appId: '1:399674068229:ios:5cb2784341b69f704fbb6c',
    messagingSenderId: '399674068229',
    projectId: 'flugram-55f95',
    storageBucket: 'flugram-55f95.appspot.com',
    iosBundleId: 'com.example.flugram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-wqLCR6eoitcRZnaMkdViIuYo7rlO27U',
    appId: '1:399674068229:ios:5cb2784341b69f704fbb6c',
    messagingSenderId: '399674068229',
    projectId: 'flugram-55f95',
    storageBucket: 'flugram-55f95.appspot.com',
    iosBundleId: 'com.example.flugram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwhwQR-_6JxCkHAWcPiB6h4pniSyFLy8Q',
    appId: '1:399674068229:web:da4356e72caea6a64fbb6c',
    messagingSenderId: '399674068229',
    projectId: 'flugram-55f95',
    authDomain: 'flugram-55f95.firebaseapp.com',
    storageBucket: 'flugram-55f95.appspot.com',
    measurementId: 'G-BE3R08XH1F',
  );
}
